/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playzone;

import playzone.SessionLogin;
//import com.mysql.cj.Session;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import javax.swing.JOptionPane;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import playzone.SessionLogin;
import playzone.homePegawai;

/**
 *
 * @author user
 */
public class CatatanHadir extends javax.swing.JFrame {
    public Statement st;
    public PreparedStatement ps;
    public ResultSet rs;
    java.sql.Connection cobakonek=playzone.Koneksi_db.configDB(); //penting
    /**
     * Creates new form CatatanHadir
     */
    public CatatanHadir() {
        this.setUndecorated(true); 
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        loadDataToTable();
      //  generateAutoID(String presensi, String ID_presensi, String PRS);
        String idPegawai = SessionLogin.getID_pegawai();
        jTextField1id.setText(String.valueOf(idPegawai)); // set ke textfield
        jTextField1id.setEditable(false); // optional, biar user ga bisa ubah
        
         // Ambil NAMA dari DB berdasarkan ID Pegawai
        try {
            String sql = "SELECT nama FROM pegawai WHERE id_pegawai = ?";
            PreparedStatement pst = cobakonek.prepareStatement(sql);
            pst.setString(1, idPegawai);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String nama = rs.getString("nama");
                jTextField2nama.setText(nama); // ⬅️ Ganti sesuai nama textfield kamu
                jTextField2nama.setEditable(false); // opsional: biar user ga bisa ngedit
            } else {
                jTextField2nama.setText("Nama tidak ditemukan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil nama pegawai: " + e.getMessage());
        }
    }
    
        private String generateAutoID(String presensi, String ID_presensi, String PRS) {
            String newID = "";
            try {
                String sql = "SELECT MAX(" + ID_presensi + ") FROM " + presensi;
                PreparedStatement pst = cobakonek.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    String maxID = rs.getString(1);
                    if (maxID != null && maxID.startsWith(PRS)) {
                        int number = Integer.parseInt(maxID.substring(PRS.length())) + 1;
                        newID = PRS + number; 
                    } else {
                        newID = PRS + "1";
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error generate ID: " + e.getMessage());
            }
            return newID;
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1check = new javax.swing.JButton();
        jTextField1id = new javax.swing.JTextField();
        jTextField2nama = new javax.swing.JTextField();
        jButton2back = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1check.setContentAreaFilled(false);
        jButton1check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn check-in.png"))); // NOI18N
        jButton1check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1checkActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1check, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, -1, 90));

        jTextField1id.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        jTextField1id.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1id.setBorder(null);
        jTextField1id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1idActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1id, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 300, 40));

        jTextField2nama.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        jTextField2nama.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2nama.setBorder(null);
        jTextField2nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2namaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 320, 50));

        jButton2back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn back absen.png"))); // NOI18N
        jButton2back.setContentAreaFilled(false);
        jButton2back.setLabel("");
        jButton2back.setContentAreaFilled(false);
        jButton2back.setBorderPainted(false);
        jButton2back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2backActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 693, 300, 80));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagi", "Sore" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 170, 190, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Presensi", "ID Pegawai", "Nama ", "Shift", "Tanggal", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 1260, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bg no catatan kehadiran.png"))); // NOI18N
        jLabel1.setLabelFor(jPanel1);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1idActionPerformed

    private void jTextField2namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2namaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1checkActionPerformed
    String id_pegawai = SessionLogin.getID_pegawai(); // ambil dari session login
    String nama = "";
    String shift = (String) jComboBox1.getSelectedItem(); // ambil shift yang dipilih user
    String status = "Hadir";
    String id_Presensi = generateAutoID("presensi", "id_presensi", "PRS");

    // Ambil nama pegawai dari database
    try {
        
        String sql = "SELECT nama FROM pegawai WHERE id_pegawai = ?";
        PreparedStatement pst = cobakonek.prepareStatement(sql);
        pst.setString(1, id_pegawai);

        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            nama = rs.getString("nama");
        } else {
            JOptionPane.showMessageDialog(this, "Pegawai tidak ditemukan");
            return; // stop proses kalau pegawai tidak ditemukan
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil nama pegawai: " + e.getMessage());
        return;
    }

    // Simpan ke tabel presensi (tanggal otomatis pakai NOW())
    try {
        String sql = "INSERT INTO presensi (ID_presensi, ID_pegawai, nama, shift, tanggal, status) VALUES (?, ?, ?, ?, NOW(), ?)";
        PreparedStatement pst = cobakonek.prepareStatement(sql);
        pst.setString(1, id_Presensi);
        pst.setString (2, id_pegawai);
        pst.setString(3, nama);
        pst.setString(4, shift);
        pst.setString(5, status);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Check-In berhasil!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal Check-In: " + e.getMessage());
    }

    loadDataToTable(); // update isi jTable

    }//GEN-LAST:event_jButton1checkActionPerformed

    private void jButton2backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2backActionPerformed
        // TODO add your handling code here:
             homePegawai brg = new homePegawai();
         brg.setVisible(true);
         dispose();
    }//GEN-LAST:event_jButton2backActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTextField1id.setOpaque(false);
        jTextField1id.setBackground(new Color(0,0,0,0));
        jTextField1id.setBorder(null);
        jTextField1id.setForeground(Color.WHITE);
        jTextField1id.setCaretColor(Color.WHITE);
        
        jTextField2nama.setOpaque(false);
        jTextField2nama.setBackground(new Color(0,0,0,0));
        jTextField2nama.setBorder(null);
        jTextField2nama.setForeground(Color.WHITE);
        jTextField2nama.setCaretColor(Color.WHITE);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatatanHadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatatanHadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatatanHadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatatanHadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatatanHadir().setVisible(true);
            }
        });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1check;
    private javax.swing.JButton jButton2back;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1id;
    private javax.swing.JTextField jTextField2nama;
    // End of variables declaration//GEN-END:variables

   private void loadDataToTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // reset isi tabel

    String idPegawai = SessionLogin.getID_pegawai(); // ambil ID dari session login

    try {
        String sql = "SELECT ID_presensi, ID_pegawai, nama, shift, tanggal, status FROM presensi WHERE ID_pegawai = ? ORDER BY tanggal DESC";
        PreparedStatement pst = cobakonek.prepareStatement(sql);
        pst.setString(1, idPegawai); // set parameter id_pegawai

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String idPresensi = rs.getString("ID_presensi");
            String idPegawaiResult = rs.getString("ID_pegawai");
            String nama = rs.getString("nama");
            String shift = rs.getString("shift");
            String tanggal = rs.getString("tanggal");
            String status = rs.getString("status");

            model.addRow(new Object[]{idPresensi, idPegawaiResult, nama, shift, tanggal, status});
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load tabel: " + e.getMessage());
    }
}



}
