/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package playzone;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class dataPS_admin extends javax.swing.JFrame {
    public Statement st;
    public PreparedStatement ps;
    public ResultSet rs;
    Connection cobakonek=playzone.Koneksi_db.configDB(); //penting, koneksi untuk menyambungkan ke database
    //untuk update data
    boolean editMode = false;
    String selectedID = "";
        
    public dataPS_admin() {
        this.setUndecorated(true); 
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        showdata(); //menampilkan data di tabel
        clearTextField(); //membersihkan isi dari jTextField dan jComboBox
        updateEditModeUI();
    }

    private String generateAutoID(String table, String column, String prefix) {
        String newID = prefix + "1";
        try {
            String sql = "SELECT " + column + " FROM " + table + " WHERE " + column + " LIKE '" + prefix + "%'";
            PreparedStatement pst = cobakonek.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            int maxNumber = 0;

            while (rs.next()) {
                String id = rs.getString(1);
                if (id != null && id.startsWith(prefix)) {
                    try {
                        int number = Integer.parseInt(id.substring(prefix.length()));
                        if (number > maxNumber) {
                            maxNumber = number;
                        }
                    } catch (NumberFormatException e) {
                        // Abaikan jika ID tidak bisa diparse
                    }
                }
            }

            newID = prefix + (maxNumber + 1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error generate ID: " + e.getMessage());
        }
        return newID;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jButtonDataEmployee = new javax.swing.JButton();
        jButtonDataSnack = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldNama = new javax.swing.JTextField();
        jComboBoxKategori = new javax.swing.JComboBox<>();
        jTextFieldHargaVIP = new javax.swing.JTextField();
        jTextFieldHargaRegular = new javax.swing.JTextField();
        jTextFieldHargaSewa12 = new javax.swing.JTextField();
        jTextFieldHargaSewa24 = new javax.swing.JTextField();
        jComboBoxKondisi = new javax.swing.JComboBox<>();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jButtonMode = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1375, 770));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                FormWindowOpened(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(1375, 770));
        jPanel1.setMinimumSize(new java.awt.Dimension(1375, 770));
        jPanel1.setPreferredSize(new java.awt.Dimension(1375, 770));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonHome.setContentAreaFilled(false);
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn isi home.png"))); // NOI18N
        jButtonHome.setContentAreaFilled(false);
        jButtonHome.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk isi home.png"))); // NOI18N
        jButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseExited(evt);
            }
        });
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 230, 80));

        jButtonDataEmployee.setContentAreaFilled(false);
        jButtonDataEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn isi Employee.png"))); // NOI18N
        jButtonDataEmployee.setContentAreaFilled(false);
        jButtonDataEmployee.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk isi Employee.png"))); // NOI18N
        jButtonDataEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDataEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDataEmployeeMouseExited(evt);
            }
        });
        jButtonDataEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDataEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 190, 40));

        jButtonDataSnack.setContentAreaFilled(false);
        jButtonDataSnack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn isi Snack.png"))); // NOI18N
        jButtonDataSnack.setContentAreaFilled(false);
        jButtonDataSnack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk isi Snack.png"))); // NOI18N
        jButtonDataSnack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDataSnackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDataSnackMouseExited(evt);
            }
        });
        jButtonDataSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataSnackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDataSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 170, 50));

        jButtonLogout.setContentAreaFilled(false);
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn isi logout.png"))); // NOI18N
        jButtonLogout.setContentAreaFilled(false);
        jButtonLogout.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk isi logout.png"))); // NOI18N
        jButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogoutMouseExited(evt);
            }
        });
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 230, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PS", "Nama", "Kategori", "Harga VIP", "Harga Regular", "Harga Sewa-12", "Harga Sewa-24", "Kondisi", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 84, 1020, 360));

        jTextFieldNama.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextFieldNama.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNama.setBorder(null);
        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 350, 40));

        jComboBoxKategori.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jComboBoxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sewa", "VIP", "Regular" }));
        jPanel1.add(jComboBoxKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 350, 30));

        jTextFieldHargaVIP.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextFieldHargaVIP.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldHargaVIP.setText("0");
        jTextFieldHargaVIP.setBorder(null);
        jTextFieldHargaVIP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldHargaVIPKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldHargaVIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 480, 270, 40));

        jTextFieldHargaRegular.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextFieldHargaRegular.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldHargaRegular.setText("0");
        jTextFieldHargaRegular.setBorder(null);
        jTextFieldHargaRegular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldHargaRegularKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldHargaRegular, new org.netbeans.lib.awtextra.AbsoluteConstraints(1086, 532, 240, 50));

        jTextFieldHargaSewa12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextFieldHargaSewa12.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldHargaSewa12.setText("0");
        jTextFieldHargaSewa12.setBorder(null);
        jTextFieldHargaSewa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaSewa12ActionPerformed(evt);
            }
        });
        jTextFieldHargaSewa12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldHargaSewa12KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldHargaSewa12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 592, 240, 40));

        jTextFieldHargaSewa24.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextFieldHargaSewa24.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldHargaSewa24.setText("0");
        jTextFieldHargaSewa24.setBorder(null);
        jTextFieldHargaSewa24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaSewa24ActionPerformed(evt);
            }
        });
        jTextFieldHargaSewa24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldHargaSewa24KeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldHargaSewa24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1084, 649, 240, 40));

        jComboBoxKondisi.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jComboBoxKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "normal", "bermasalah", "rusak" }));
        jPanel1.add(jComboBoxKondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 350, 30));

        jComboBoxStatus.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kosong", "diservis" }));
        jPanel1.add(jComboBoxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 650, 350, 30));

        jButtonMode.setContentAreaFilled(false);
        jButtonMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn edit.png"))); // NOI18N
        jButtonMode.setContentAreaFilled(false);
        jButtonMode.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk edit.png"))); // NOI18N
        jButtonMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 708, 310, 50));

        jButtonSave.setContentAreaFilled(false);
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn save data.png"))); // NOI18N
        jButtonSave.setContentAreaFilled(false);
        jButtonSave.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk save data.png"))); // NOI18N
        jButtonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSaveMouseExited(evt);
            }
        });
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 708, 390, 50));

        jButtonDelete.setContentAreaFilled(false);
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn delete.png"))); // NOI18N
        jButtonDelete.setContentAreaFilled(false);
        jButtonDelete.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk delete.png"))); // NOI18N
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 709, 310, -1));

        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bg no Playstation inventory.png"))); // NOI18N
        jLabel1.setText("hahaha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void FormWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FormWindowOpened
        // Bikin tulisan tabel berada di tengah
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Terapkan rata tengah ke semua kolom di tabel
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Tampilkan garis tabel antar sel
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.LIGHT_GRAY);
        
        jTextFieldNama.setOpaque(false);
        jTextFieldNama.setBackground(new Color(0,0,0,0));
        jTextFieldNama.setBorder(null);
        jTextFieldNama.setForeground(Color.WHITE);
        jTextFieldNama.setCaretColor(Color.WHITE);
        
        jTextFieldHargaVIP.setOpaque(false);
        jTextFieldHargaVIP.setBackground(new Color(0,0,0,0));
        jTextFieldHargaVIP.setBorder(null);
        jTextFieldHargaVIP.setForeground(Color.WHITE);
        jTextFieldHargaVIP.setCaretColor(Color.WHITE);
        
        jTextFieldHargaRegular.setOpaque(false);
        jTextFieldHargaRegular.setBackground(new Color(0,0,0,0));
        jTextFieldHargaRegular.setBorder(null);
        jTextFieldHargaRegular.setForeground(Color.WHITE);
        jTextFieldHargaRegular.setCaretColor(Color.WHITE);
        
        jTextFieldHargaSewa12.setOpaque(false);
        jTextFieldHargaSewa12.setBackground(new Color(0,0,0,0));
        jTextFieldHargaSewa12.setBorder(null);
        jTextFieldHargaSewa12.setForeground(Color.WHITE);
        jTextFieldHargaSewa12.setCaretColor(Color.WHITE);
        
        jTextFieldHargaSewa24.setOpaque(false);
        jTextFieldHargaSewa24.setBackground(new Color(0,0,0,0));
        jTextFieldHargaSewa24.setBorder(null);
        jTextFieldHargaSewa24.setForeground(Color.WHITE);
        jTextFieldHargaSewa24.setCaretColor(Color.WHITE);
    }//GEN-LAST:event_FormWindowOpened

    private void jButtonSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButtonSaveMouseExited

    private void jButtonSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButtonSaveMouseEntered

    private void jButtonLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButtonLogoutMouseExited

    private void jButtonLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogoutMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButtonLogoutMouseEntered

    private void jButtonDataSnackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDataSnackMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButtonDataSnackMouseExited

    private void jButtonDataSnackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDataSnackMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButtonDataSnackMouseEntered

    private void jButtonDataEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDataEmployeeMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButtonDataEmployeeMouseExited

    private void jButtonDataEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDataEmployeeMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButtonDataEmployeeMouseEntered

    private void jButtonHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButtonHomeMouseExited

    private void jButtonHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButtonHomeMouseEntered

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
                String id_ps = generateAutoID("playstation", "ID_playstation", "PS");

            // Ambil data dari input
            String Nama = jTextFieldNama.getText().trim();
            String Kategori = jComboBoxKategori.getSelectedItem().toString();
            String hargaVIPText = jTextFieldHargaVIP.getText().trim();
            String hargaRegularText = jTextFieldHargaRegular.getText().trim();
            String hargaSewa12Text = jTextFieldHargaSewa12.getText().trim();
            String hargaSewa24Text = jTextFieldHargaSewa24.getText().trim();
            String Kondisi = jComboBoxKondisi.getSelectedItem().toString();
            String Status = jComboBoxStatus.getSelectedItem().toString();

            // Notifikasi input tidak boleh kosong untuk field wajib selain harga
            if (Nama.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Cek minimal satu harga harus diisi
            if (hargaVIPText.equals("0") && hargaRegularText.equals("0") && hargaSewa12Text.equals("0") && hargaSewa24Text.equals("0")) {
                JOptionPane.showMessageDialog(null, "Minimal salah satu harga harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }



            // Konversi angka untuk harga
            double hargaVIP = Double.parseDouble(hargaVIPText);
            double hargaRegular = Double.parseDouble(hargaRegularText);
            double hargaSewa12 = Double.parseDouble(hargaSewa12Text);
            double hargaSewa24 = Double.parseDouble(hargaSewa24Text);

            // kode SQL untuk tambah data atau update data menggunakan IF
            if (!editMode) {
                // INSERT atau tambah data
                String sql = "INSERT INTO playstation (ID_playstation, Nama_barang, kategori, harga_VIP, harga_regular, harga_sewa12, harga_sewa24, kondisi, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = cobakonek.prepareStatement(sql);

                pst.setString(1, id_ps);
                pst.setString(2, Nama);
                pst.setString(3, Kategori);
                pst.setDouble(4, hargaVIP);
                pst.setDouble(5, hargaRegular);
                pst.setDouble(6, hargaSewa12);
                pst.setDouble(7, hargaSewa24);
                pst.setString(8, Kondisi);
                pst.setString(9, Status);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
                
            } else {
                // UPDATE
                String sql = "UPDATE playstation SET Nama_barang=?, kategori=?, harga_VIP=?, harga_regular=?, harga_sewa12=?, harga_sewa24=?, kondisi=?, status=? WHERE ID_playstation=?";
                PreparedStatement pst = cobakonek.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
                
                pst.setString(1, Nama);
                pst.setString(2, Kategori);
                pst.setDouble(3, hargaVIP);
                pst.setDouble(4, hargaRegular);
                pst.setDouble(5, hargaSewa12);
                pst.setDouble(6, hargaSewa24);
                pst.setString(7, Kondisi);
                pst.setString(8, Status);
                pst.setString(9, selectedID);
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
            }
            
            // Refresh table dan clear form
            showdata();
            clearTextField();
            editMode = false;
            selectedID = "";
            updateEditModeUI();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Pastikan semua harga diisi dengan angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal simpan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            //  int id = (int) jTable1.getValueAt(selectedRow, 0);

            int confirm = JOptionPane.showConfirmDialog(
                    null,
                    "Apakah kamu ingin mengedit data ini ?",
                    "Konfirmasi Edit",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {    
                editMode = true; // Aktifkan mode edit
                selectedID = jTable1.getValueAt(selectedRow, 0).toString();
                updateEditModeUI();

                jTextFieldNama.setText(jTable1.getValueAt(selectedRow, 1).toString());
                jComboBoxKategori.setSelectedItem(jTable1.getValueAt(selectedRow, 2).toString());
                jTextFieldHargaVIP.setText(jTable1.getValueAt(selectedRow, 3).toString());
                jTextFieldHargaRegular.setText(jTable1.getValueAt(selectedRow, 4).toString());
                jTextFieldHargaSewa12.setText(jTable1.getValueAt(selectedRow, 5).toString());
                jTextFieldHargaSewa24.setText(jTable1.getValueAt(selectedRow, 6).toString());
                jComboBoxKondisi.setSelectedItem(jTable1.getValueAt(selectedRow, 7).toString());
                jComboBoxStatus.setSelectedItem(jTable1.getValueAt(selectedRow, 8).toString());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextFieldHargaSewa12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaSewa12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaSewa12ActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
       /*login logout = new login();
        logout.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonDataSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataSnackActionPerformed
       /* datasnack dataPS = new datasnack();
        dataPS.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButtonDataSnackActionPerformed

    private void jButtonDataEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataEmployeeActionPerformed
       /* datapegawai dataPS = new datapegawai();
        dataPS.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButtonDataEmployeeActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus!");
        return;
        }

        String IDps = (String) jTable1.getValueAt(selectedRow, 0); // Kolom 1 adalah ID_playstation

        // Konfirmasi sebelum menghapus
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM playstation WHERE ID_playstation = ?";

            try {
                PreparedStatement stat = cobakonek.prepareStatement(sql);
                stat.setString(1, IDps);
                stat.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                clearTextField();
                showdata();
                editMode = false;
                selectedID = "";
                updateEditModeUI();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error saat menghapus data: " + e.getMessage());
            }
        } 
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModeActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            null,
            "Apakah Anda yakin ingin membatalkan pengeditan?\nPerubahan yang belum disimpan akan hilang!",
            "Konfirmasi Batal Edit",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            editMode = false;
            selectedID = "";
            clearTextField();
            updateEditModeUI();
            JOptionPane.showMessageDialog(null, "Edit mode dibatalkan.");
        }
    }//GEN-LAST:event_jButtonModeActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        homeAdmin nw_transaksi = new homeAdmin();
        nw_transaksi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jTextFieldHargaSewa24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaSewa24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaSewa24ActionPerformed

    private void jTextFieldHargaVIPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHargaVIPKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b') {
            evt.consume(); // Cegah input selain angka
        }
    }//GEN-LAST:event_jTextFieldHargaVIPKeyTyped

    private void jTextFieldHargaRegularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHargaRegularKeyTyped
       char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b') {
            evt.consume(); // Cegah input selain angka
        }
    }//GEN-LAST:event_jTextFieldHargaRegularKeyTyped

    private void jTextFieldHargaSewa12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHargaSewa12KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b') {
            evt.consume(); // Cegah input selain angka
        }
    }//GEN-LAST:event_jTextFieldHargaSewa12KeyTyped

    private void jTextFieldHargaSewa24KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHargaSewa24KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b') {
            evt.consume(); // Cegah input selain angka
        }
    }//GEN-LAST:event_jTextFieldHargaSewa24KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataPS_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataPS_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataPS_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataPS_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataPS_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDataEmployee;
    private javax.swing.JButton jButtonDataSnack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonMode;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxKategori;
    private javax.swing.JComboBox<String> jComboBoxKondisi;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldHargaRegular;
    private javax.swing.JTextField jTextFieldHargaSewa12;
    private javax.swing.JTextField jTextFieldHargaSewa24;
    private javax.swing.JTextField jTextFieldHargaVIP;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables

    // Method untuk menampilkan data dari database ke jTabel 
    private void showdata() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            String sql = "SELECT * FROM playstation"; //WHERE ID_Pegawai = ? ---- ini kalau difilter pake sesi login aktif
            ps = cobakonek.prepareStatement(sql); //ps.setInt(1, SessionLogin.getID_pegawai()); // Panggil dari session
            rs = ps.executeQuery();

            while (rs.next()) {
                String ID_Playstation = rs.getString("ID_playstation");
                String Nama = rs.getString("Nama_barang");
                String Kategori = rs.getString("kategori");
                int hargaVIP = rs.getInt("harga_VIP");
                int hargaRegular = rs.getInt("harga_regular");
                int hargaSewa12 = rs.getInt("harga_sewa12");
                int hargaSewa24 = rs.getInt("harga_sewa24");
                String Kondisi = rs.getString("kondisi");
                String Status = rs.getString("status");

                Object[] Rowdata = {ID_Playstation, Nama, Kategori, hargaVIP, hargaRegular, hargaSewa12, hargaSewa24, Kondisi, Status};
                model.addRow(Rowdata);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    
    // Method untuk membersihkan tulisan yg ada pada jTextField dan jComboBox
    private void clearTextField() {
        jTextFieldNama.setText("");
        jComboBoxKategori.setSelectedItem(null);
        jTextFieldHargaVIP.setText("0");    
        jTextFieldHargaRegular.setText("0");
        jTextFieldHargaSewa12.setText("0");
        jTextFieldHargaSewa24.setText("0");
        jComboBoxKondisi.setSelectedItem(null);
        jComboBoxStatus.setSelectedItem(null);
    }
    
    private void updateEditModeUI() {
        if (editMode) {
          //  jLabelMode.setText("Mode Edit: ON");
            jButtonMode.setEnabled(true);
            jButtonDelete.setEnabled(true);
        } else {
           // jLabelMode.setText("Mode Edit: OFF");
            jButtonMode.setEnabled(false);
            jButtonDelete.setEnabled(false);
        }
    }
    
}
