/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playzone;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class homeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form homeAdmin
     */
    public homeAdmin() {
        this.setUndecorated(true); 
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1Datapegawai = new javax.swing.JButton();
        jButton2Dataps = new javax.swing.JButton();
        jButton3Snack = new javax.swing.JButton();
        jButton1logout = new javax.swing.JButton();
        jButton1exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1375, 770));
        jPanel1.setPreferredSize(new java.awt.Dimension(1375, 770));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1Datapegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn employee data.png"))); // NOI18N
        jButton1Datapegawai.setContentAreaFilled(false);
        jButton1Datapegawai.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk employee data.png"))); // NOI18N
        jButton1Datapegawai.setLabel("");
        jButton1Datapegawai.setContentAreaFilled(false);
        jButton1Datapegawai.setBorderPainted(false);
        jButton1Datapegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1DatapegawaiActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Datapegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 200, 300));

        jButton2Dataps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn PS inventor.png"))); // NOI18N
        jButton2Dataps.setContentAreaFilled(false);
        jButton2Dataps.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk PS inventor.png"))); // NOI18N
        jButton2Dataps.setLabel("");
        jButton2Dataps.setContentAreaFilled(false);
        jButton2Dataps.setBorderPainted(false);
        jButton2Dataps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2DatapsActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2Dataps, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 200, 300));

        jButton3Snack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn snack inventor.png"))); // NOI18N
        jButton3Snack.setContentAreaFilled(false);
        jButton3Snack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk snack inventor.png"))); // NOI18N
        jButton3Snack.setLabel("");
        jButton3Snack.setContentAreaFilled(false);
        jButton3Snack.setBorderPainted(false);
        jButton3Snack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3SnackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3Snack, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 200, 300));

        jButton1logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn logout home adm.png"))); // NOI18N
        jButton1logout.setContentAreaFilled(false);
        jButton1logout.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk logout home adm.png"))); // NOI18N
        jButton1logout.setLabel("");
        jButton1logout.setContentAreaFilled(false);
        jButton1logout.setBorderPainted(false);
        jButton1logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1logoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, 370, 140));

        jButton1exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn exit home.png"))); // NOI18N
        jButton1exit.setContentAreaFilled(false);
        jButton1exit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk exit home adm.png"))); // NOI18N
        jButton1exit.setLabel("");
        jButton1exit.setContentAreaFilled(false);
        jButton1exit.setBorderPainted(false);
        jButton1exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1exitActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, 370, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bg no Home Admin.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2DatapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2DatapsActionPerformed
        dataPS_admin dataPS = new dataPS_admin();
        dataPS.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2DatapsActionPerformed

    private void jButton1DatapegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1DatapegawaiActionPerformed
        /* datapegawai dataP = new datapegawai();
        dataP.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButton1DatapegawaiActionPerformed

    private void jButton3SnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3SnackActionPerformed
       /*  datasnack dataP = new datasnack();
        dataP.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButton3SnackActionPerformed

    private void jButton1logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1logoutActionPerformed
     /* int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah anda yakin ingin keluar?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                SessionLogin.clearSession();
                login backToLogin = new login();
                backToLogin.setVisible(true);
                this.dispose();
            }       */ 
    
    }//GEN-LAST:event_jButton1logoutActionPerformed

    private void jButton1exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1exitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah anda yakin ingin menutup aplikasi?",
                "Konfirmasi exit",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                SessionLogin.clearSession();
                System.exit(0);
            }
    }//GEN-LAST:event_jButton1exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Datapegawai;
    private javax.swing.JButton jButton1exit;
    private javax.swing.JButton jButton1logout;
    private javax.swing.JButton jButton2Dataps;
    private javax.swing.JButton jButton3Snack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
