/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playzone;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import playzone.SessionLogin;


/**
 *
 * @author USER
 */
public class homePegawai extends javax.swing.JFrame {

    /**
     * Creates new form homePegawai
     */
    public homePegawai() {
        this.setUndecorated(true); 
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1snack = new javax.swing.JButton();
        jButton2onspot = new javax.swing.JButton();
        jButton4presensi = new javax.swing.JButton();
        jButton5report = new javax.swing.JButton();
        jButton6logout = new javax.swing.JButton();
        jButton7exit = new javax.swing.JButton();
        jButton1sewa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1375, 770));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1snack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn home snack.png"))); // NOI18N
        jButton1snack.setContentAreaFilled(false);
        jButton1snack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk home snack.png"))); // NOI18N
        jButton1snack.setLabel("");
        jButton1snack.setContentAreaFilled(false);
        jButton1snack.setBorderPainted(false);
        jButton1snack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1snackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1snack, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 190, 300));

        jButton2onspot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn home main.png"))); // NOI18N
        jButton2onspot.setContentAreaFilled(false);
        jButton2onspot.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk home main.png"))); // NOI18N
        jButton2onspot.setLabel("");
        jButton2onspot.setContentAreaFilled(false);
        jButton2onspot.setBorderPainted(false);
        jButton2onspot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2onspotActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2onspot, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 200, 300));

        jButton4presensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn presence record.png"))); // NOI18N
        jButton4presensi.setContentAreaFilled(false);
        jButton4presensi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk presence record.png"))); // NOI18N
        jButton4presensi.setLabel("");
        jButton4presensi.setContentAreaFilled(false);
        jButton4presensi.setBorderPainted(false);
        jButton4presensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4presensiActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4presensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 320, 410, 110));

        jButton5report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn home report.png"))); // NOI18N
        jButton5report.setContentAreaFilled(false);
        jButton5report.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk home report.png"))); // NOI18N
        jButton5report.setLabel("");
        jButton5report.setContentAreaFilled(false);
        jButton5report.setBorderPainted(false);
        jButton5report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5reportActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5report, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 200, 300));

        jButton6logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn logout home peg.png"))); // NOI18N
        jButton6logout.setContentAreaFilled(false);
        jButton6logout.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk logout home peg.png"))); // NOI18N
        jButton6logout.setLabel("");
        jButton6logout.setContentAreaFilled(false);
        jButton6logout.setBorderPainted(false);
        jButton6logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6logoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 470, 340, 120));

        jButton7exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn exit home peg.png"))); // NOI18N
        jButton7exit.setContentAreaFilled(false);
        jButton7exit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk exit home peg.png"))); // NOI18N
        jButton7exit.setLabel("");
        jButton7exit.setContentAreaFilled(false);
        jButton7exit.setBorderPainted(false);
        jButton7exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7exitActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 610, 340, 120));

        jButton1sewa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn home sewa.png"))); // NOI18N
        jButton1sewa.setContentAreaFilled(false);
        jButton1sewa.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk home sewa.png"))); // NOI18N
        jButton1sewa.setLabel("");
        jButton1sewa.setContentAreaFilled(false);
        jButton1sewa.setBorderPainted(false);
        jButton1sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1sewaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 200, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bg no Home Pegawai.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1snackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1snackActionPerformed
     /*transaksiSnack nw_transaksi = new transaksiSnack();
        nw_transaksi.setVisible(true);
        this.dispose();*/
    
    }//GEN-LAST:event_jButton1snackActionPerformed

    private void jButton2onspotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2onspotActionPerformed
        /*transaksiMainDitempat nw_transaksi = new transaksiMainDitempat();
        nw_transaksi.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButton2onspotActionPerformed

    private void jButton4presensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4presensiActionPerformed
        CatatanHadir nw_transaksi = new CatatanHadir();
        nw_transaksi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4presensiActionPerformed

    private void jButton7exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7exitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah anda yakin ingin menutup aplikasi?",
                "Konfirmasi exit",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                SessionLogin.clearSession();
                System.exit(0);
            }
    }//GEN-LAST:event_jButton7exitActionPerformed

    private void jButton5reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5reportActionPerformed
      /* LprnSewa LPsewa = new LprnSewa();
        LPsewa.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButton5reportActionPerformed

    private void jButton6logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6logoutActionPerformed
      /*int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah anda yakin ingin keluar?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                SessionLogin.clearSession();
                login backToLogin = new login();
                backToLogin.setVisible(true);
                this.dispose();
            }*/
    }//GEN-LAST:event_jButton6logoutActionPerformed

    private void jButton1sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1sewaActionPerformed
       /* TrSewaPegawai TRsewa = new TrSewaPegawai();
        TRsewa.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButton1sewaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1sewa;
    private javax.swing.JButton jButton1snack;
    private javax.swing.JButton jButton2onspot;
    private javax.swing.JButton jButton4presensi;
    private javax.swing.JButton jButton5report;
    private javax.swing.JButton jButton6logout;
    private javax.swing.JButton jButton7exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
