/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playzone;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import playzone.dataPS_admin;
//import playzone.datapegawai;
//import playzone.datasnack;
//import playzone.homeAdmin;

/**
 *
 * @author user
 */
public class RekapAdmin  extends javax.swing.JFrame {
    public Statement st;
    public PreparedStatement ps;
    public ResultSet rs;
    Connection cobakonek=playzone.Koneksi_db.configDB(); //penting
    /**
     * Creates new form RekapAdmin
     */
    public RekapAdmin() throws SQLException {
            this.setUndecorated(true);
            initComponents();
            tampilkanData();
            jComboBox1ActionPerformed(null);
           this.setExtendedState(JFrame.MAXIMIZED_BOTH);


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonH = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonLog = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonPs = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn isi home.png"))); // NOI18N
        jButtonH.setContentAreaFilled(false);
        jButtonH.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk isi home.png"))); // NOI18N
        jButtonH.setLabel("");
        jButtonH.setContentAreaFilled(false);
        jButtonH.setBorderPainted(false);
        jButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, 90));

        jComboBox1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attendance", "Data management" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 32, 360, 40));

        jButtonLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn isi logout.png"))); // NOI18N
        jButtonLog.setContentAreaFilled(false);
        jButtonLog.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk isi logout.png"))); // NOI18N
        jButtonLog.setLabel("");
        jButtonLog.setContentAreaFilled(false);
        jButtonLog.setBorderPainted(false);
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 240, -1));

        jButtonS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn isi Snack.png"))); // NOI18N
        jButtonS.setContentAreaFilled(false);
        jButtonS.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk isi Snack.png"))); // NOI18N
        jButtonS.setLabel("");
        jButtonS.setContentAreaFilled(false);
        jButtonS.setBorderPainted(false);
        jButtonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 190, 60));

        jButtonPs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn isi PlayStation.png"))); // NOI18N
        jButtonPs.setContentAreaFilled(false);
        jButtonPs.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk isi PlayStation.png"))); // NOI18N
        jButtonPs.setLabel("");
        jButtonPs.setContentAreaFilled(false);
        jButtonPs.setBorderPainted(false);
        jButtonPs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPs, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 200, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pegawai", "Nama", "Shift", "Tanggal", "Status"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 167, 970, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bg no attendance.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selected = (String) jComboBox1.getSelectedItem();
           if (selected.equals("Data management")) {
               //datapegawai dataManagementFrame = new datapegawai();               
              // dataManagementFrame.setVisible(true);
              //this.dispose();           
           }     
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHActionPerformed
        /*homeAdmin nw_transaksi = new homeAdmin();
        nw_transaksi.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButtonHActionPerformed

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin ingin logout?", "Logout", JOptionPane.YES_NO_OPTION);
        
        // Jika memilih YES, logout
        if (confirm == JOptionPane.YES_OPTION) {
            // Menutup aplikasi (jika ini aplikasi desktop)
            System.exit(0); 
        } else {
            // Tidak ada aksi jika memilih NO
            System.out.println("Logout dibatalkan.");
        }
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void jButtonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSActionPerformed
        /*datasnack nw_transaksi = new datasnack();
        nw_transaksi.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_jButtonSActionPerformed

    private void jButtonPsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPsActionPerformed
        //dataPS_admin nw_transaksi = new dataPS_admin();
        //nw_transaksi.setVisible(true);
        this.dispose();    }//GEN-LAST:event_jButtonPsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RekapAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RekapAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RekapAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RekapAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
          
            public void run() {
                try {
                    new RekapAdmin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RekapAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonPs;
    private javax.swing.JButton jButtonS;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

 


    private void tampilkanData() {    

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // clear tabel        
        try {
            String sql = "SELECT p.ID_pegawai, p.Shift, pg.Nama, p.Tanggal, p.status FROM presensi p " +
                         "JOIN pegawai pg ON p.ID_pegawai = pg.ID_pegawai";            
            ps = cobakonek.prepareStatement(sql); 
            rs = ps.executeQuery();            
            while (rs.next()) {       
                String idPegawai = rs.getString("ID_pegawai");                
                String nama =rs.getString("Nama");
                String shift =rs.getString("Shift");                
                String tgl = rs.getString("Tanggal");
                String status = rs.getString("status");                        
                Object[] Rowdata = {idPegawai, nama, shift, tgl, status};                
                model.addRow(Rowdata); 
            }
        }      
        //  jTable1.setModel(model);
        catch (Exception e) {        
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }    
    }
}
