/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectelis;

import projectelis.login;
import projectelis.Koneksi_db;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import projectelis.Koneksi_db;

public class register extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Koneksi_db DB = new Koneksi_db();
    
    public register() {
        this.setUndecorated(true); 
        initComponents();
        RF.requestFocusInWindow();
        DB.configDB();
        con = DB.koneksi;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
        private void reset() {
                username_r.setText("");
                name.setText("");
                phone.setText("");
                password_r.setText("");
            }

        private String generateAutoID(String table, String column, String prefix) {
        String newID = prefix + "1";
        try {
            String sql = "SELECT " + column + " FROM " + table + " WHERE " + column + " LIKE '" + prefix + "%'";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            int maxNumber = 0;

            while (rs.next()) {
                String id = rs.getString(1);
                if (id != null && id.startsWith(prefix)) {
                    try {
                        int number = Integer.parseInt(id.substring(prefix.length()));
                        if (number > maxNumber) {
                            maxNumber = number;
                        }
                    } catch (NumberFormatException e) {
                        // Abaikan jika ID tidak bisa diparse
                    }
                }
            }

            newID = prefix + (maxNumber + 1);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error generate ID: " + e.getMessage());
        }
        return newID;
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username_r = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        create_a = new javax.swing.JButton();
        sign_in = new javax.swing.JButton();
        level = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        RF = new javax.swing.JTextField();
        pw = new javax.swing.JTextField();
        password_r = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                FrameWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_r.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        username_r.setForeground(new java.awt.Color(255, 255, 255));
        username_r.setBorder(null);
        username_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_rActionPerformed(evt);
            }
        });
        jPanel1.add(username_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 434, 480, 50));

        name.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 204, 480, 50));

        phone.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setBorder(null);
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 289, 480, 40));

        create_a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn create account.png"))); // NOI18N
        create_a.setContentAreaFilled(false);
        create_a.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk create account.png"))); // NOI18N
        create_a.setLabel("");
        create_a.setContentAreaFilled(false);
        create_a.setBorderPainted(false);
        create_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_aActionPerformed(evt);
            }
        });
        jPanel1.add(create_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 653, 620, 60));

        sign_in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn sign in.png"))); // NOI18N
        sign_in.setContentAreaFilled(false);
        sign_in.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk sign in.png"))); // NOI18N
        sign_in.setLabel("");
        sign_in.setContentAreaFilled(false);
        sign_in.setBorderPainted(false);
        sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_inActionPerformed(evt);
            }
        });
        jPanel1.add(sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 710, 110, 50));

        level.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setText("Pegawai");
        level.setBorder(null);
        level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelActionPerformed(evt);
            }
        });
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 590, 480, 50));

        jButton1.setLabel("");
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/btn exit register.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/efk exit register.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 690, 260, 80));

        RF.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        RF.setForeground(new java.awt.Color(255, 255, 255));
        RF.setBorder(null);
        RF.setName(""); // NOI18N
        RF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFActionPerformed(evt);
            }
        });
        RF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RFKeyTyped(evt);
            }
        });
        jPanel1.add(RF, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 359, 480, 50));

        pw.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        pw.setForeground(new java.awt.Color(255, 255, 255));
        pw.setBorder(null);
        jPanel1.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 522, 480, 30));

        password_r.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bg no register.png"))); // NOI18N
        jPanel1.add(password_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_rActionPerformed
 
    private void FrameWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FrameWindowOpened
        name.setOpaque(false);  // Membuat JTextField transparan
        name.setBackground(new Color(0,0,0,0)); // Membuat background benar-benar transparan
        name.setBorder(null);   // Menghapus border
        name.setForeground(Color.WHITE);  // Warna teks menjadi putih
        name.setCaretColor(Color.WHITE);
        
        phone.setOpaque(false);  // Membuat JTextField transparan
        phone.setBackground(new Color(0,0,0,0)); // Membuat background benar-benar transparan
        phone.setBorder(null);   // Menghapus border
        phone.setForeground(Color.WHITE);  // Warna teks menjadi putih
        phone.setCaretColor(Color.WHITE);
        
        RF.setOpaque(false);  // Membuat JTextField transparan
        RF.setBackground(new Color(0,0,0,0)); // Membuat background benar-benar transparan
        RF.setBorder(null);   // Menghapus border
        RF.setForeground(Color.WHITE);  // Warna teks menjadi putih
        RF.setCaretColor(Color.WHITE);
        
        username_r.setOpaque(false);  // Membuat JTextField transparan
        username_r.setBackground(new Color(0,0,0,0)); // Membuat background benar-benar transparan
        username_r.setBorder(null);   // Menghapus border
        username_r.setForeground(Color.WHITE);  // Warna teks menjadi putih
        username_r.setCaretColor(Color.WHITE);

        pw.setOpaque(false);  // Membuat JTextField transparan
        pw.setBackground(new Color(0,0,0,0)); // Membuat background benar-benar transparan
        pw.setBorder(null);   // Menghapus border
        pw.setForeground(Color.WHITE);  // Warna teks menjadi putih
        pw.setCaretColor(Color.WHITE);
     
        level.setOpaque(false);  // Membuat JTextField transparan
        level.setBackground(new Color(0,0,0,0)); // Membuat background benar-benar transparan
        level.setBorder(null);   // Menghapus border
        level.setForeground(Color.WHITE);  // Warna teks menjadi putih
        level.setCaretColor(Color.WHITE);
    }//GEN-LAST:event_FrameWindowOpened

    private void create_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_aActionPerformed
        try {
            String idAkunBaru = generateAutoID("akun", "ID_akun", "AKN");
            String idPegawai = generateAutoID("pegawai", "ID_pegawai", "PGW");
        // Cek apakah username dan level sudah digunakan
        String sqlCheck = "SELECT COUNT(*) AS count FROM akun WHERE username = ? AND level = ?";
        pst = con.prepareStatement(sqlCheck);
        pst.setString(1, username_r.getText());
        pst.setString(2, level.getText());
        rs = pst.executeQuery();

        if (rs.next() && rs.getInt("count") > 0) {
            JOptionPane.showMessageDialog(null, "Username sudah digunakan untuk level ini!");
        } else {
            // INSERT ke tabel akun
            String sqlInsertAkun = "INSERT INTO akun (ID_akun, ID_kartuRFID, username, password, level) VALUES (?, ?, ?, ?, ?)";
            pst = con.prepareStatement(sqlInsertAkun, Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, idAkunBaru); 
            pst.setString(2, RF.getText());
            pst.setString(3, username_r.getText());
            pst.setString(4, pw.getText());
            pst.setString(5, level.getText());
            pst.executeUpdate();
            
            // Ambil ID_akun dari akun yang baru dimasukkan
            rs = pst.getGeneratedKeys();
           // String idAkunBaru;
            if (rs.next()) {
                idAkunBaru = rs.getString(1);
            }
            rs.close();
            pst.close();

            // INSERT ke tabel pegawai (ID_pegawai auto-increment, jadi tidak diset manual)
            String sqlInsertPegawai = "INSERT INTO pegawai (ID_pegawai, nama, no_hp, ID_akun) VALUES ( ?, ?, ?, ?)";
            pst = con.prepareStatement(sqlInsertPegawai, Statement.RETURN_GENERATED_KEYS); 

            pst.setString(1, idPegawai); 
            pst.setString(2, name.getText());
            pst.setString(3, phone.getText());
            pst.setString(4, idAkunBaru);

            if (pst.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Register berhasil!");
                reset();
            }
            pw.setText("");
            RF.setText("");
            pst.close();
        }

        login sign_in = new login();
        sign_in.setVisible(true);
        this.dispose();
        
        if (rs != null) rs.close();
        if (pst != null) pst.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }

    }//GEN-LAST:event_create_aActionPerformed

    private void levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelActionPerformed
        level.setEditable(false);
        level.setText("Pegawai");
    }//GEN-LAST:event_levelActionPerformed

    private void sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_inActionPerformed
        login sign_in = new login();
        sign_in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sign_inActionPerformed

    private void RFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFActionPerformed
        String idRFID = RF.getText();
    
    // Misalnya kamu tampilkan di console atau proses data
    System.out.println("ID RFID: " + idRFID);
    
    // Kosongkan field agar siap untuk input berikutnya
  //  RF.setText("");
    
    // Fokus kembali ke JTextField
    RF.requestFocusInWindow();
    }//GEN-LAST:event_RFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b') {
            evt.consume(); // Cegah input selain angka
        }
    }//GEN-LAST:event_phoneKeyTyped

    private void RFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RFKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b') {
            evt.consume(); // Cegah input selain angka
        }
    }//GEN-LAST:event_RFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RF;
    private javax.swing.JButton create_a;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField level;
    private javax.swing.JTextField name;
    private javax.swing.JLabel password_r;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pw;
    private javax.swing.JButton sign_in;
    private javax.swing.JTextField username_r;
    // End of variables declaration//GEN-END:variables
}
